// <auto-generated />
using System;
using LoanDefaultPrediction.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanDefaultPrediction.Web.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20260708163743_AddPrecisionRecallConfusionMatrix")]
    partial class AddPrecisionRecallConfusionMatrix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LoanDefaultPrediction.Web.Data.LoanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Age")
                        .HasColumnType("REAL");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("CreditScore")
                        .HasColumnType("REAL");

                    b.Property<float>("DebtToIncomeRatio")
                        .HasColumnType("REAL");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Income")
                        .HasColumnType("REAL");

                    b.Property<float>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<float>("LoanAmount")
                        .HasColumnType("REAL");

                    b.Property<float>("LoanTerm")
                        .HasColumnType("REAL");

                    b.Property<float>("MonthsEmployed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LoanRecords");
                });

            modelBuilder.Entity("LoanDefaultPrediction.Web.Data.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<float>("AreaUnderRoc")
                        .HasColumnType("REAL");

                    b.Property<string>("ConfusionMatrixJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("F1Score")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PfiMetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Precision")
                        .HasColumnType("REAL");

                    b.Property<float>("Recall")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
